//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Ivayyva
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Дом.
    /// </summary>
    // *** Start programmer edit section *** (Дом CustomAttributes)

    // *** End programmer edit section *** (Дом CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДомE", new string[] {
            "Тип as \'Тип\'",
            "Класс as \'Класс\'",
            "Класс.Действие as \'Действие\'"}, Hidden=new string[] {
            "Класс.Действие"})]
    [MasterViewDefineAttribute("ДомE", "Класс", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Действие")]
    [View("ДомL", new string[] {
            "Тип as \'Тип\'",
            "Класс.Действие as \'Действие\'"})]
    public class Дом : ICSSoft.STORMNET.DataObject
    {
        
        private int fТип;
        
        private IIS.Ivayyva.Класс fКласс;
        
        // *** Start programmer edit section *** (Дом CustomMembers)

        // *** End programmer edit section *** (Дом CustomMembers)

        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Дом.Тип CustomAttributes)

        // *** End programmer edit section *** (Дом.Тип CustomAttributes)
        public virtual int Тип
        {
            get
            {
                // *** Start programmer edit section *** (Дом.Тип Get start)

                // *** End programmer edit section *** (Дом.Тип Get start)
                int result = this.fТип;
                // *** Start programmer edit section *** (Дом.Тип Get end)

                // *** End programmer edit section *** (Дом.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Дом.Тип Set start)

                // *** End programmer edit section *** (Дом.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Дом.Тип Set end)

                // *** End programmer edit section *** (Дом.Тип Set end)
            }
        }
        
        /// <summary>
        /// Дом.
        /// </summary>
        // *** Start programmer edit section *** (Дом.Класс CustomAttributes)

        // *** End programmer edit section *** (Дом.Класс CustomAttributes)
        [PropertyStorage(new string[] {
                "Класс"})]
        [NotNull()]
        public virtual IIS.Ivayyva.Класс Класс
        {
            get
            {
                // *** Start programmer edit section *** (Дом.Класс Get start)

                // *** End programmer edit section *** (Дом.Класс Get start)
                IIS.Ivayyva.Класс result = this.fКласс;
                // *** Start programmer edit section *** (Дом.Класс Get end)

                // *** End programmer edit section *** (Дом.Класс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Дом.Класс Set start)

                // *** End programmer edit section *** (Дом.Класс Set start)
                this.fКласс = value;
                // *** Start programmer edit section *** (Дом.Класс Set end)

                // *** End programmer edit section *** (Дом.Класс Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДомE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДомE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДомE", typeof(IIS.Ivayyva.Дом));
                }
            }
            
            /// <summary>
            /// "ДомL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДомL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДомL", typeof(IIS.Ivayyva.Дом));
                }
            }
        }
    }
}
