//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Ivayyva
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Класс.
    /// </summary>
    // *** Start programmer edit section *** (Класс CustomAttributes)

    // *** End programmer edit section *** (Класс CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлассE", new string[] {
            "Действие as \'Действие\'"})]
    [View("КлассL", new string[] {
            "Действие as \'Действие\'"})]
    public class Класс : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Ivayyva.tДействие fДействие;
        
        // *** Start programmer edit section *** (Класс CustomMembers)

        // *** End programmer edit section *** (Класс CustomMembers)

        
        /// <summary>
        /// Действие.
        /// </summary>
        // *** Start programmer edit section *** (Класс.Действие CustomAttributes)

        // *** End programmer edit section *** (Класс.Действие CustomAttributes)
        public virtual IIS.Ivayyva.tДействие Действие
        {
            get
            {
                // *** Start programmer edit section *** (Класс.Действие Get start)

                // *** End programmer edit section *** (Класс.Действие Get start)
                IIS.Ivayyva.tДействие result = this.fДействие;
                // *** Start programmer edit section *** (Класс.Действие Get end)

                // *** End programmer edit section *** (Класс.Действие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Класс.Действие Set start)

                // *** End programmer edit section *** (Класс.Действие Set start)
                this.fДействие = value;
                // *** Start programmer edit section *** (Класс.Действие Set end)

                // *** End programmer edit section *** (Класс.Действие Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлассE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассE", typeof(IIS.Ivayyva.Класс));
                }
            }
            
            /// <summary>
            /// "КлассL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассL", typeof(IIS.Ivayyva.Класс));
                }
            }
        }
    }
}
